### ISSUE TITLE
Sintetizar função execv/forks

### ISSUE THREAD

**Issue by rodsmade** [rodsmade/Minishell-42sp#3]
- [x] fork
- [x] wait
- [x] waitpid
- [x] wait3
- [x] wait4
- [x] access
- [x] execve
- [x] dup
- [x] dup2
- [x] pipe

**Comment by rodsmade** [comment]
REF CABULOSA:
https://github.com/MickeyMighty/MiniShell

**Comment by rodsmade** [comment]
sobre wait3 e wait4: " These functions are nonstandard; in new programs, the use of waitpid(2) or waitid(2) is preferable." 🤷

**Comment by rodsmade** [comment]
fork, wait/waitpid, access, execve, dup/dup2 e pipe usamos no pipex respectivamente pra:
criar um processo filho que vai rodar um comando do path (execve), isso pq a execve encerra o processo q a chamou, então se não fizer fork, o programa como um todo é encerrado e ñ eh isso o q queremos; pra controlar o fluxo de execução do(s) processo(s) filho(s); pra validar se arquivos existem/têm permissão de leitura; pra rodar comandos do path; pra redirercionar file descriptors e pra criar arquivos de escrita/leitura pros processos consecutivos se comunicarem

**Comment by adrianofaus** [comment]
Fork-> System call that creates a new process (child process) which runs concurrently with the process that makes the fork (parent process). Both parent and child processes use the same resources.
Return
-> Negative, value means that creation of a child process was unsuccessful.
-> Zero, Returned to the newly created child process.
-> Positive value, Return to parent. The value is the ID of newly created child process.

Comment: Very useful function to use with execv. This is because, execve replaces all resources of current process by another process. At the end, when one forks a process they can use execv on the new process whitout losing all resources from the main process.

Source: https://www.geeksforgeeks.org/fork-system-call/

**Comment by adrianofaus** [comment]
Wait-> System call that blocks the calling process until one of its child process terminate. A child process may terminate due to any of these:
->It Calls exit();
->It returns an int from main;
->It receives a terminate signal from OS.

When a child terminates its reported the following information:
->normal/abnormal termination
->termination cause
->exit status

It's possible to hold the status of a child using the following:
WIFEXITED(status): child exited normally 
WEXITSTATUS(status): return code when child exits
WIFSIGNALED(status): child exited because a signal was not caught WTERMSIG(status): gives the number of the terminating signal
WIFSTOPPED(status): child is stopped 
WSTOPSIG(status): gives the number of the stop signal

There are also options to use with wait
-> 0, Means no option parent has to wait for terminates child.
-> WNOHANG, Means parent does not wait if a child does not terminates. In another words, does not block the parent process.

Comment: Usually wait is used with fork. When a process is forked then the parent has to wait for its child terminates. Commonly, fork is used when one wants to do something in parallel with another process.

**Comment by adrianofaus** [comment]
Access-> Checks whether the calling program has access to a specified file. Following modes that can be used:
F_OK flag : Used to check for existence of file.
R_OK flag : Used to check for read permission bit.
W_OK flag : Used to check for write permission bit.
X_OK flag : Used to check for execute permission bit.

Comment: Access is a very useful command to check a file before the use of exec function family.

https://www.geeksforgeeks.org/access-command-in-linux-with-examples/

**Comment by adrianofaus** [comment]
Execve-> Executes the program refered to by pathname. When exec function is used it consumes all recourses from the calling process.

Comment: Usually it's usued after a fork to run a process inside another process.

https://man7.org/linux/man-pages/man2/execve.2.html

**Comment by adrianofaus** [comment]
Dup and Dup2 -> These are functions used to duplicate an opened file descriptor. The difference between them are:
-> Dup, duplicates a file descriptor and assign the lowest file descriptor number for the new one;
-> Dup2, duplicates a file descriptor and assign the preferable file descriptor number for the new one.

**Comment by adrianofaus** [comment]
Pipe -> Creates a two way channel for processes to communicate. It receives two integers, usually two file descriptors and assign the following for them:
-> Position 0 is used for reading;
-> Position 1 is used for writing.

Comment: A process can write on a fd and another process can read from it. This is really useful when dealing with forks, because one may wants a parent process to read from a child process.
